# Generated by Django 4.1.11 on 2023-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
