# Generated by Django 4.1.11 on 2023-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_date_joined_devicedata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_cam',
            field=models.BooleanField(default=False),
        ),
    ]
