# Generated by Django 4.1.11 on 2023-09-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH_sensor_data', models.CharField(default='', max_length=17, null=True, unique=True)),
                ('T_sensor_data', models.CharField(default='', max_length=17, null=True, unique=True)),
                ('TDS_sensor_data', models.CharField(default='', max_length=17, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.device')),
            ],
        ),
    ]
