# Generated by Django 4.1.11 on 2023-09-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_device_is_cam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
    ]
