# Generated by Django 4.1.11 on 2023-09-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_devicedata_ph_sensor_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='PH_sensor_data',
            field=models.IntegerField(default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='TDS_sensor_data',
            field=models.IntegerField(default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='T_sensor_data',
            field=models.IntegerField(default='', null=True, unique=True),
        ),
    ]
