# Generated by Django 4.1.11 on 2023-10-15 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_devstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devstat',
            old_name='hv_version',
            new_name='hw_version',
        ),
    ]
